version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
        NODE_VERSION: '${NODE_VERSION:-18}'
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app

networks:
  default:
    driver: bridge